channels = {
    "oe1": {
        "shortname": "oe1",
        "streamurl": "http://mp3ooe1.apasf.sf.apa.at/;",
        "streamurlShoutcast2": "http://oe1shoutcast.sf.apa.at:8000/;",
        "strmtype": "audio/mpeg",
        "tracklist": "http://hop.orf.at/img-trackservice/oe1.js",
        "curProgram": "http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp",
        "leftbuttonstring": "Hitlist",
        "midbuttonstring": "Podcasts",
        "infodata": "./infos/oe1infos.html",
        "aticon": "./images/oe1-aticon.png",
        "statncss": "./css/oe1.css",
        "stationname": "Radio Österreich 1",
        "cHasData": False,
        "cPrimaryColor": "#b11a1a",
        "cSecondaryColor": "#ffffff",
        "cStationName": "Radio Ö1"

    },
    "oe3": {
        "shortname": "oe3",
        "streamurl": "http://mp3oe3.apasf.sf.apa.at/;",
        "streamurlShoutcast2": "http://oe3shoutcast.sf.apa.at:8000/;",
        "strmtype": "audio/mpeg",
        "tracklist": "http://ms01.oe3.fm/oe3metafiles/RMX/RMWEB.PHP?Res=200&Format=json&callback=onair&Type=long",
        "curProgram": "http://ms01.oe3.fm/oe3metafiles/ModAK/ShowInfo.php?ImgRes=HD&InfoType=Full&Format=json&callback=sendung",
        "leftbuttonstring": "Hitlist",
        "midbuttonstring": "Podcasts",
        "infodata": "./infos/oe3infos.html",
        "aticon": "./images/oe3-aticon.png",
        "statncss": "./css/oe3b.css",
        "chcolor": "#f04040",
        "stationname": "hitradio Ö3",
        "cHasData": True,
        "cPrimaryColor": "#002350",
        "cSecondaryColor": "#E10032",
        "cStationName": "Hitradio Ö3"

    },
    "fm4": {
        "shortname": "fm4",
        "streamurl": "http://mp3fm4.apasf.sf.apa.at/;",
        "streamurlShoutcast2": "http://fm4shoutcast.sf.apa.at:8000/;",
        "strmtype": "audio/mpeg",
        "tracklist": "http://hop.orf.at/img-trackservice/fm4.js",
        "curProgram": "http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=Wochen-Plan-Fm4.xml",
        "leftbuttonstring": "Hitlist",
        "midbuttonstring": "Podcasts",
        "infodata": "./infos/fm4infos.html",
        "aticon": "./images/fm4-aticon.png",
        "statncss": "./css/fm4b.css",
        "stationname": "Radio FM4",
        "cHasData": True,
        "cPrimaryColor": "#FFE500",
        "cSecondaryColor": "#000000",
    },
    "bgl": {
        "shortname": "bgl",
        "streamurl": "http://mp3burgenland.apasf.sf.apa.at/;",
        "streamurlShoutcast2": "http://oe2bshoutcast.sf.apa.at:8000/;",
        "strmtype": "audio/mpeg",
        "tracklist": "http://hop.orf.at/img-trackservice/bgl.js",
        "curProgram": "http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-bgl.xml",
        "leftbuttonstring": "Hitlist",
        "midbuttonstring": "Podcasts",
        "infodata": "./infos/bglinfos.html",
        "aticon": "./images/bgl-aticon.png",
        "anicon": "./images/bgl-aticon-128.png",
        "statncss": "./css/bgl.css",
        "stationname": "Radio Burgenland",
        "cHasData": True,
        "cPrimaryColor": "#ffa60f",
        "cSecondaryColor": "#d32824"
    },
    "ktn": {
        "shortname": "ktn",
        "streamurl": "http://mp3kaernten.apasf.sf.apa.at/;",
        "streamurlShoutcast2": "http://oe2kshoutcast.sf.apa.at:8000/;",
        "strmtype": "audio/mpeg",
        "tracklist": "http://hop.orf.at/img-trackservice/ktn.js",
        "curProgram": "http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-ktn.xml",
        "leftbuttonstring": "Tracklist",
        "midbuttonstring": "",
        "infodata": "./infos/ktninfos.html",
        "aticon": "./images/ktn-aticon.png",
        "statncss": "./css/ktn.css",
        "stationname": "Radio Kärnten",
        "cHasData": False,
        "cPrimaryColor": "#bc1716",
        "cSecondaryColor": "#ffcd00"
    },
    "noe": {
        "shortname": "noe",
        "streamurl": "http://mp3noe.apasf.sf.apa.at/;",
        "streamurlShoutcast2": "http://oe2nshoutcast.sf.apa.at:8000/;",
        "strmtype": "audio/mpeg",
        "tracklist": "http://hop.orf.at/img-trackservice/noe.js",
        "curProgram": "http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-noe.xml",
        "leftbuttonstring": "Hitlist",
        "midbuttonstring": "Podcasts",
        "infodata": "./infos/noeinfos.html",
        "aticon": "./images/noe-aticon.png",
        "statncss": "./css/noe.css",
        "stationname": "Radio Niederösterreich",
        "cHasData": True,
        "cPrimaryColor": "#002777",
        "cSecondaryColor": "#ffcd00"
    },
    "ooe": {
        "shortname": "ooe",
        "streamurl": "http://mp3ooe.apasf.sf.apa.at/;",
        "streamurlShoutcast2": "http://oe2oshoutcast.sf.apa.at:8000/;",
        "strmtype": "audio/mpeg",
        "tracklist": "http://hop.orf.at/img-trackservice/ooe.js",
        "curProgram": "http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-ooe.xml",
        "leftbuttonstring": "Hitlist",
        "midbuttonstring": "",
        "infodata": "./infos/ooeinfos.html",
        "aticon": "./images/ooe-aticon.png",
        "statncss": "./css/ooe.css",
        "stationname": "Radio Oberösterreich",
        "deskstream": "http://orfradio.liwest.at/liveHQ.m3u",
        "cHasData": True,
        "cPrimaryColor": "#bc1716",
        "cSecondaryColor": "#ffffff"
    },
    "sbg": {
        "shortname": "sbg",
        "streamurl": "http://mp3salzburg.apasf.sf.apa.at/;",
        "streamurlShoutcast2": "http://oe2sshoutcast.sf.apa.at:8000/;",
        "strmtype": "audio/mpeg",
        "tracklist": "http://hop.orf.at/img-trackservice/sbg.js",
        "curProgram": "http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-sbg.xml",
        "leftbuttonstring": "Hitlist",
        "midbuttonstring": "",
        "infodata": "./infos/sbginfos.html",
        "aticon": "./images/sbg-aticon.png",
        "splash": "./images/sbg-splash.png",
        "statncss": "./css/sbg.css",
        "stationname": "Radio Salzburg",
        "cHasData": True,
        "cPrimaryColor": "#bc1716",
        "cSecondaryColor": "#ffffff"
    },
    "stm": {
        "shortname": "stm",
        "streamurl": "http://mp3stmrk.apasf.sf.apa.at/;",
        "streamurlShoutcast2": "http://oe2stshoutcast.sf.apa.at:8000/;",
        "strmtype": "audio/mpeg",
        "tracklist": "http://hop.orf.at/img-trackservice/stmk.js",
        "curProgram": "http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-stm.xml",
        "leftbuttonstring": "Hitlist",
        "midbuttonstring": "Podcasts",
        "infodata": "./infos/stminfos.html",
        "aticon": "./images/stm-aticon.png",
        "statncss": "./css/stm.css",
        "stationname": "Radio Steiermark",
        "cHasData": True,
        "cPrimaryColor": "#006843",
        "cSecondaryColor": "#ffffff"
    },
    "tir": {
        "shortname": "tir",
        "streamurl": "http://mp3tirol.apasf.sf.apa.at/;",
        "streamurlShoutcast2": "http://oe2tshoutcast.sf.apa.at:8000/;",
        "strmtype": "audio/mpeg",
        "tracklist": "http://hop.orf.at/img-trackservice/tir.js",
        "curProgram": "http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-tir.xml",
        "leftbuttonstring": "Hitlist",
        "midbuttonstring": "Podcasts",
        "infodata": "./infos/tirinfos.html",
        "aticon": "./images/tir-aticon.png",
        "statncss": "./css/tir.css",
        "stationname": "Radio Tirol",
        "cHasData": True,
        "cPrimaryColor": "#bc1716",
        "cSecondaryColor": "#ffffff"
    },
    "vbg": {
        "shortname": "vbg",
        "streamurl": "http://mp3vlbg.apasf.sf.apa.at/;",
        "streamurlShoutcast2": "http://oe2vshoutcast.sf.apa.at:8000/;",
        "strmtype": "audio/mpeg",
        "tracklist": "http://hop.orf.at/img-trackservice/vbg.js",
        "curProgram": "http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-vbg.xml",
        "leftbuttonstring": "Hitlist",
        "midbuttonstring": "Podcasts",
        "infodata": "./infos/vbginfos.html",
        "aticon": "./images/vbg-aticon.png",
        "statncss": "./css/vbg.css",
        "stationname": "Radio Vorarlberg",
        "cHasData": False,
        "cPrimaryColor": "#bc1716",
        "cSecondaryColor": "#ffffff"
    },
    "wie": {
        "shortname": "wie",
        "streamurl": "http://mp3wien2.apasf.sf.apa.at/;",
        "streamurlShoutcast2": "http://oe2wshoutcast.sf.apa.at:8000/;",
        "strmtype": "audio/mpeg",
        "tracklist": "http://hop.orf.at/img-trackservice/wien.js",
        "curProgram": "http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-wie.xml",
        "leftbuttonstring": "Hitlist",
        "midbuttonstring": "Podcasts",
        "infodata": "./infos/wieinfos.html",
        "aticon": "./images/wie-aticon.png",
        "splash": "./images/wie-splash.png",
        "statncss": "./css/wie.css",
        "stationname": "Radio Wien",
        "cHasData": True,
        "cPrimaryColor": "#ee7e01",
        "cSecondaryColor": "#552382"
    },
    "kht": {
        "shortname": "kht",
        "stationname": "Kronehit",
        "cHasData": True,
        "cPrimaryColor": "#000000",
        "cSecondaryColor": "#b89c4f"
    },
    "886": {
        "shortname": "886",
        "stationname": "Radio 88.6",
        "cHasData": True,
        "cPrimaryColor": "#123e6b",
        "cSecondaryColor": "#ffe116"
    },
    "ara": {
        "shortname": "ara",
        "stationname": "Radio Arabella",
        "cHasData": True,
        "cPrimaryColor": "#003e88",
        "cSecondaryColor": "#e6007e"
    },
    "eng": {
        "shortname": "eng",
        "stationname": "Engergy Wien/Nö/Bgld",
        "cHasData": True,
        "cPrimaryColor": "#000000",
        "cSecondaryColor": "#E2001A"
    },
    "all": {
        "shortname": "all",
        "stationname": "Alle",
        "cHasData": True,
        "cPrimaryColor": "black",
        "cSecondaryColor": "white"
    }
}
